### ISSUE TITLE
Parallisation is hard coded to use 2 cores

### ISSUE THREAD

**Issue by gowerc** [Genentech/psborrow#10]
Looks like `run_mcmc_p` (the parallelised version of `run_mcmc`) is hard coded to use 2 cores:

```
  # nCluster <- parallel::detectCores()
  nCluster <- 2 # switch to 2 cluster per CRAN's requirement
  message(nCluster, " clusters are being used")
```

Might be worth clarifying if this functionality is needed and if so making it dynamic (also maybe merging it with run_mcmc to have just a single function).

**Comment by gowerc** [comment]
I think for this I would propse that we just add a simple change of adding `ncores` as a variable to the function

**Comment by danielinteractive** [comment]
Simple change sounds good.
