### ISSUE TITLE
User Guide Typos

### ISSUE THREAD

**Issue by gowerc** [Genentech/psborrow#11]
In the user guide, there are a few extra "$$" signs, which might be small typos around the formula. The team might want to remove it for the next version.

**Comment by gowerc** [comment]
I couldn't see this at all in the current user guide however I would say this is dependent on #17 before to confirm it doesn't occur in any of the other vignettes before closing this ticket

**Comment by mattsecrest** [comment]
@gowerc I could not find any extra `$$` in the current user guide. Are you able to find any? If not, maybe we can close this one.
