### ISSUE TITLE
Potentially unused packages

### ISSUE THREAD

**Issue by gowerc** [Genentech/psborrow#12]
RCMDCHECK comes up with the following:

```
N  checking dependencies in R code (1.6s)
   Namespaces in Imports field not imported from:
     ‘matrixcalc’ ‘tidyr’ ‘utils’
```

Need to check if these packages are used or not and remove from the DESCRIPTION file if they aren't (or downgrade to suggests if they are only used in vignettes)

**Comment by danielinteractive** [comment]
Yes, it would be good to fix this.
