### ISSUE TITLE
Add CICD to publish github pages

### ISSUE THREAD

**Issue by gowerc** [Genentech/psborrow#14]
Would be good if we could use cicd to publish the vignettes via github pages. This is pretty trivial by taking the existing insights engineering templates but need to consolidate what the source of the current published materials are to make sure we aren't duplicating available resources.

**Comment by danielinteractive** [comment]
If it is simple then let's do it. As you say, Herb and Jiawen might still have some static copies elsewhere, but that is not too bad I think
