### ISSUE TITLE
Add CICD to do full CRAN checks

### ISSUE THREAD

**Issue by gowerc** [Genentech/psborrow#16]
CRAN generally wants you to have run R CMD CHECK against multiple versions of R as well as the current/ previous / future release of R. Current plan is to implement this as a manually executed workflow.

**Comment by danielinteractive** [comment]
I would give this low priority, given overall strategy. I would expect like maximum one more CRAN release this year, so value is limited.

**Comment by gowerc** [comment]
Fair enough, I figure we can just manually run rhub checks for now
