### ISSUE TITLE
Synchronise internal and public repo

### ISSUE THREAD

**Issue by gowerc** [Genentech/psborrow#17]
For reference our internal repo contains the following files that are not in this repo:

```
data/demo_exp.rda
data/demo_weibull.rda
images/bg_hr.png
images/blacktocat.png
images/icon_download.png
images/sprite_download.png
vignettes/demo.Rmd
vignettes/DLBCL_use_case.Rmd
stylesheets/github-light.css
stylesheets/stylesheet.css
index.html
params.json
```

Would be good to pull as many of these forward to this repo as possible, though may require digging into why they are not apart of this repo to begin with.

More confusingly it looks like there might be divergences between the 2 repos, for example `vignettes/user_guide.Rmd ` is different between the internal & external one. We may need to scan the two repos to see what other deviations there are and if they need to be carried forward or not

**Comment by danielinteractive** [comment]
vignettes/demo.Rmd: parts of this can be inspiration for the analysis vignette.

vignettes/DLBCL_use_case.Rmd: contains closer references to study data. Therefore we don't want to share those.

Minor number changes in the external vs. internal documents were deliberate to obfuscate internal study details.

**Comment by mattsecrest** [comment]
Closing following conversation with @gowerc
