### ISSUE TITLE
Support / guidance for running analysis

### ISSUE THREAD

**Issue by gowerc** [Genentech/psborrow#18]
An item we discussed was creating a vignette/guidance for how to use the package to run analysis on a non-simulated dataset. Are any code changes required to make this easier or is it purely just making the documentation better?

**Comment by danielinteractive** [comment]
Yeah I would say let's discuss this with Herb and Jiawen in upcoming meeting, this could be one that they can actually do.

**Comment by danielinteractive** [comment]
Next step: @JiawenZhuxm and Herb will have a look into it and come back.

**Comment by JiawenZhuxm** [comment]
Indeed we will need additional functions. A single case can be run through run_mcmc function, but it includes a wrapper on result summary. We will need to add a function for single trial analysis using the same mcmc steps in the run_mcmc function, but also add statistical inference/interpretation.

**Comment by JiawenZhuxm** [comment]
single dataset can be analyzed by add_mcmc with column requirement: c("driftHR", "HR", "trt", "ext", "time", "cnsr").

driftHR and HR are not used I think. 
Output example:

[add_mcmc] cov_name = cov1 cov2 cov3 
Input all is found in pred. Any other input is disregarded.
>>> prior = cauchy , pred =  all 
[r_post] dt = driftHR HR ext trt cov1 cov2 cov3 time cnsr 
[r_post] cov_name = cov1 cov2 cov3 
All covariates cov1 cov2 cov3 are used as predictors in the weibull distribution. Any other input is disregarded. 
[r_post] N = 500 event = 272 ext = 125 n_cov = 3 x = trt cov1 cov2 cov3 
[r_post] r0 = 1 alpha = 0 0 beta = 0 0 0 0 sigma = 0.03 .RNG.seed =  1 
  |**************************************************| 100%

Iterations = 1002:6001
Thinning interval = 1 
Number of chains = 2 
Sample size per chain = 5000 

1. Empirical mean and standard deviation for each variable,
   plus standard error of the mean:

                Mean        SD  Naive SE Time-series SE
HR_cc_hc   9.108e-01 1.121e-01 1.121e-03      2.702e-03
HR_trt_cc  6.607e-01 9.652e-02 9.652e-04      2.475e-03
alpha[1]  -4.838e+00 5.700e-01 5.700e-03      1.009e-01
alpha[2]  -4.736e+00 5.641e-01 5.641e-03      9.421e-02
beta[1]   -4.249e-01 1.445e-01 1.445e-03      3.679e-03
beta[2]    2.920e-02 1.522e-01 1.522e-03      2.270e-03
beta[3]   -9.184e-02 1.218e-01 1.218e-03      2.292e-03
beta[4]    1.113e-02 8.470e-03 8.470e-05      1.255e-03
prec       1.709e+04 3.646e+05 3.646e+03      5.876e+03
r0         9.952e-01 5.077e-02 5.077e-04      2.774e-03

2. Quantiles for each variable:

               2.5%       25%      50%       75%      97.5%
HR_cc_hc   0.667491  0.838359  0.92772   0.99406  1.097e+00
HR_trt_cc  0.493259  0.592765  0.65339   0.72136  8.713e-01
alpha[1]  -5.810237 -5.237502 -4.88877  -4.50084 -3.489e+00
alpha[2]  -5.695815 -5.147728 -4.76174  -4.39731 -3.421e+00
beta[1]   -0.706721 -0.522958 -0.42558  -0.32662 -1.378e-01
beta[2]   -0.282787 -0.071531  0.03196   0.13310  3.138e-01
beta[3]   -0.337333 -0.169925 -0.09070  -0.01115  1.453e-01
beta[4]   -0.007389  0.005757  0.01165   0.01726  2.533e-02
prec       1.042611 11.483156 46.40874 212.65597  1.808e+04
r0         0.890613  0.961743  0.99533   1.02938  1.093e+00

[1] "reject TRUE mean_HR 0.660703318953011 sd_HR 0.0965181304257949 mean_driftHR 0.910759034380488 sd_driftHR 0.11205387867685"
