### ISSUE TITLE
`plot_type1error()` does not display properly

### ISSUE THREAD

**Issue by mattsecrest** [Genentech/psborrow#19]
Running a simplified version of the vignette, I am not able to see the type 1 error plot:

![image](https://user-images.githubusercontent.com/35199424/160322929-d90bb133-b25e-43b7-88c5-3089c49143c7.png)

**Comment by mattsecrest** [comment]
MREP using the vignette verbatim 

```
ss = set_n(ssC = 200, ssE = 180, ssExt = 400)
covset1 = set_cov(n_cat = 2, n_cont = 1, 
                  mu_int = c(0, 0.5, 0.5), mu_ext = c(0.7, 0.5, 0.9), 
                  var = c(1, 1.2, 1), cov = c(0.5, 0.7, 0.9), 
                  prob_int = c(0.45, 0.55), prob_ext = c(0.65, 0.55))
covset2 = set_cov(n_cat = 2, n_cont = 3, 
                  mu_int = 0, mu_ext = 0.2, var = 0.7, cov = 0.7, 
                  prob_int = 0.5)
cov_list <- c(covset1, covset2)
sample_cov <- simu_cov(ssObj = ss, covObj = cov_list, HR = c(0.67, 1), driftHR = c(1, 1.2), nsim = 10, seed = 47)
evt = set_event(event = "pwexp", lambdaC = c(0.0135, 0.02), t_itv = 2,
                beta = c(rep(0.2,3), 0.3, rep(0.5,2), rep(2, 2)))
c_int = set_clin(gamma = c(2,3,16), e_itv = c(5,10),  CCOD = "fixed-first", CCOD_t = 45, etaC = c(0.02, 0.03), etaE = c(0.2, 0.3), d_itv = 2)
c_ext = set_clin(gamma = 10, CCOD = "event", CCOD_t = 150, etaC = 0.05)
sample_time <- simu_time(dt = sample_cov, eventObj = evt, clinInt = c_int, clinExt = c_ext, seed = 47)
pr1 <- set_prior(pred = "all", prior = "cauchy", r0 = 1, alpha = c(0, 0), sigma = 0.03)
pr2 <- set_prior(pred = "all", prior = "gamma", r0 = 1,  alpha = c(0, 0))
pr3 <- set_prior(pred = "all", prior = "no_ext", r0 = 1, alpha = 0)
pr4 <- set_prior(pred = "all", prior = "full_ext", r0 = 1, alpha = 0)
pr_list = c(pr1, pr2, pr3, pr4)
res <- run_mcmc(dt = sample_time, pr_list, n.chains = 2, n.adapt = 100, n.burn = 100, n.iter = 200, seed = 47)
summ <- get_summary(res)
plot_type1error(summ, driftHR = 1.2, pred = "all")
```

Produces:

![image](https://user-images.githubusercontent.com/35199424/160448338-a0e1b7e1-57fc-4119-9743-18686fcd9a38.png)

Compared to vignette version:

![image](https://user-images.githubusercontent.com/35199424/160448408-e6fee04e-2bd7-4008-a68f-3b68cdf861fb.png)

**Comment by mattsecrest** [comment]
A related issue is that `plot_type1error()` does not work with no HR=1 simulation.

```
> plot_type1error(summ, driftHR = 1.2, pred = "all")
Error in ans[ypos] <- rep(yes, length.out = len)[ypos] : 
  replacement has length zero
In addition: Warning message:
In rep(yes, length.out = len) : 'x' is NULL so the result will be NULL

```

**Comment by gowerc** [comment]
Just as an FYI because I stumbled across the documentation whilst looking a separate issue the following is what JAGs said about reproducibility:

![image](https://user-images.githubusercontent.com/8447209/161289530-4d161b9b-d6f2-4290-a51a-b86bf3ac5c0c.png)


It also appears to be implemented as expected (at least from a passing glance):

![image](https://user-images.githubusercontent.com/8447209/161289647-059ee2a1-9e6d-4156-bdaa-f5b66f870dac.png)

**Comment by mattsecrest** [comment]
Interesting. I get different results from the published vignette even when I go through `devtools::build_vignettes()`.

**Comment by gowerc** [comment]
re-running the vignette locally  as well as manually stepping through it are now generating identical results for me.... I currently can't reproduce the non-reproducibility issue :(
