### ISSUE TITLE
Documentation and messaging for `set_cov` could be improved

### ISSUE THREAD

**Issue by mattsecrest** [Genentech/psborrow#22]
I think we could improve `set_cov` with a few light tweaks:

- It could be clearer that the categorical variables will be made from continuous variables
- The ordering of the categorical / continuous variables is not made clear
- When only 2 variables are selected and only 1 covariance required, an unnecessary warning is issued that this value will apply to all covariances
- There are a couple of typos

**Comment by gowerc** [comment]
These all feel like reasonable (and smallish) changes to me I propose to move this to TO-DO. @danielinteractive

**Comment by danielinteractive** [comment]
sounds good - just keep it small
