### ISSUE TITLE
Helper function to summarize the mean and covariance of simulated covariates

### ISSUE THREAD

**Issue by mattsecrest** [Genentech/psborrow#26]
Because 1) `rvnorm` might have to find the closest positive definite matrix and 2) categorical covariates are based on a continuous distribution and later binarized, the true covariates will differ in mean and covariance from what the user specifies in `set_cov()`. It could be helpful to have a function that summarizes this information.

**Comment by gowerc** [comment]
Decided we wont do this but will address in the next version of the package
