### ISSUE TITLE
Better handling of incorrect inputs for `plot_*` functions

### ISSUE THREAD

**Issue by mattsecrest** [Genentech/psborrow#28]
Similar to `plot_type1error()`, the other plotting functions have uninformative errors, for instance if the specified HR is not part of the simulation summary, the following error is produced:

```
> plot_power(dt1, HR = 0.67, driftHR = 1, pred = "all")
Error in ans[ypos] <- rep(yes, length.out = len)[ypos] : 
  replacement has length zero
In addition: Warning message:
In rep(yes, length.out = len) : 'x' is NULL so the result will be NULL
```

Let's standardize the plot functions to catch these input errors as we did for `plot_type1error()` in PR https://github.com/Genentech/psborrow/pull/21

**Comment by gowerc** [comment]
This feels reasonable to me I propose to move to "TO-DO" @danielinteractive

**Comment by danielinteractive** [comment]
yes agree - I guess it is very easy and fast to add assertions on function inputs. (I recommend `checkmate` for that)
