### ISSUE TITLE
Change of maintainer

### ISSUE THREAD

**Issue by gowerc** [Genentech/psborrow#29]
I am wondering if we need to change the maintainer now that Aijing has left. 

That being said I think we might have an issue here as she has registered the package under her work email which she will no longer have access to. Apparently the CRAN process for changing the owner of a package is:

> Submit first with new DESCRIPTION file
Confirm submission on new email-address
Answer confirmation-mail sent by admin to old email-address

@danielinteractive  Any ideas here, I'm wondering if we need to work with IT ?

**Comment by danielinteractive** [comment]
I would just mention this in the CRAN submission text and give her new email address - I suppose we can figure out her new email address?
