### ISSUE TITLE
Drift HR Inconsistency

### ISSUE THREAD

**Issue by zhiiiyang** [Genentech/psborrow#59]
Hi, I noticed an inconsistency in how `driftHR` is calculated in the simulation step and the MCMC models. 

In your simulation step, `driftHR` is historical control over concurrent control.
![image](https://user-images.githubusercontent.com/7269113/203173946-b63a36d7-f0d5-40e3-b800-eed2b275cab4.png)
https://github.com/Genentech/psborrow/blob/main/R/add_time.R#L305

However, in your MCMC models, `driftHR` is the reverse. 
![image](https://user-images.githubusercontent.com/7269113/203174009-05881ef2-d5b2-45ca-b26d-cf104b4f0b2b.png)
![image](https://user-images.githubusercontent.com/7269113/203174033-e902aecf-31f4-4b83-bb15-132ce0e2a9cb.png)

Below is an example confirming the parameter was coded in the opposite way. 
![image](https://user-images.githubusercontent.com/7269113/203174248-d26fdc41-d4a2-4b78-832d-8763f2338e97.png)

Please let me know your thoughts. Thank you!

**Comment by JiawenZhuxm** [comment]
Thank you Zhi for flagging it! @mattsecrest @gowerc
